# _config.yml

# Project information
title: "Project Euler: Workbook"
author: "Jonny & Tom"
# logo: logo.png  # Optional

# Repository URL (for GitHub Pages)
repository:
  url: "https://github.com/tomctang/10pe"
  path_to_docs: "https://github.com/tomctang/10pe"
  branch: "gh-pages"  # Deployment branch for GitHub Pages

# HTML and theme configuration
#  favicon: "path/to/favicon.ico"  # Optional
# html:
#  theme:
#    name: "sphinx_book_theme"
#    options:
#      logo_only: true
#      search_bar_position: "navbar"
#      extra_navbar: '<p>My Custom Footer</p>'

html:
  use_issues_button: false
  use_repository_button: true


# Execution options
execute:
  execute_notebooks: "off"  # Change to "auto" to execute notebooks during the build
